{{- if .Values.traefik.deployment.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.traefik.fullnameOverride }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ include "traefik.hostname" . }}`)
      middlewares:
        {{- $mw := index .Values "traefik-forward-auth" "middleware" "name" }}
        {{- if .Values.cluster "home" }}
          {{- $mw := printf "%s-home" }}
        {{- end }}
        - name: {{ $mw }}
      priority: 10
      services:
        - kind: TraefikService
          name: api@internal
  tls:
    secretName: {{ include "traefik.secretname" . }}
{{- end -}}
