{{- if .Values.traefik.deployment.enabled -}}
  {{- $chartVersion := printf "%s-%s" .Chart.Name (index .Chart.Dependencies 0).Version -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: {{ $chartVersion }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: traefik
spec:
  endpoints:
    - path: /metrics
      targetPort: metrics
  jobLabel: traefik
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      helm.sh/chart: {{ $chartVersion }}
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
