global:
  cluster: do

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/external/aws
    objects:
      - name: credentials

cert-manager:
  fullnameOverride: cert-manager
  prometheus:
    servicemonitor:
      enabled: "true"
  installCRDs: true
  volumes:
    - name: aws-credentials
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: cert-manager
  volumeMounts:
    - mountPath: /.aws
      name: aws-credentials
      readOnly: true
