addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/external/aws
    objects:
      - name: credentials

cert-manager:
  fullnameOverride: cert-manager
  prometheus:
    servicemonitor:
      enabled: "true"
  installCRDs: true
  volumeMounts:
    - mountPath: /.aws
      name: aws-credentials
      readOnly: true
