global:
  fullnameOverride: readarr-ebooks

arr:
  env:
    APP_PORT: "8787"

  image:
    repository: ghcr.io/k8s-at-home/readarr
    tag: v0.1.0.991

  probes:
    liveness:
      spec:
        exec:
          command:
            - /usr/bin/env
            - bash
            - -c
            - curl --fail localhost:${APP_PORT}/${APP_NAME/-//}/api/v1/system/status?apiKey=`IFS=\> && while
              read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
