plex:
  controllerType: deployment
  fullnameOverride: plex
  image:
    repository: ghcr.io/k8s-at-home/plex
    tag: v1.22.3.4392-d7c624def
  env:
    # cat /config/Library/Application\ Support/Plex\ Media\ Server/Preferences.xml | tr " " "\n" | \
    # sed -n '/<Preferences/,$p' | tail -n +2 | sed 's,/>,,g' | \
    # sed '/\(OldestPreviousVersion\|MachineIdentifier\|^PlexOnline\|Certificate\|PubSub\|NeedsUpdate\)/d' | \
    # sed 's/"//g' | awk '{print "PLEX_PREFERENCE_"i++": \""$0"\""}'
    PLEX_PREFERENCE_0: "allowedNetworks=10.0.10.0/24,172.16.0.0/16"
    PLEX_PREFERENCE_1: "TranscoderTempDirectory=/transcode"
    PLEX_PREFERENCE_2: "FriendlyName=NickFlix"
    PLEX_PREFERENCE_3: "HardwareAcceleratedCodecs=1"
    PLEX_PREFERENCE_4: "autoEmptyTrash=1"
    PLEX_PREFERENCE_5: "ManualPortMappingPort=443"
    PLEX_PREFERENCE_6: "ScheduledLibraryUpdateInterval=86400"
    PLEX_PREFERENCE_7: "TranscoderCanOnlyRemuxVideo=0"
    PLEX_PREFERENCE_8: "HardwareAcceleratedEncoders=1"
    PLEX_PREFERENCE_9: "EnableIPv6=0"
    PLEX_PREFERENCE_10: "sendCrashReports=0"
    PLEX_PREFERENCE_11: "DlnaEnabled=0"
    PLEX_PREFERENCE_12: "ManualPortMappingMode=1"
    PLEX_PREFERENCE_13: "ScheduledLibraryUpdatesEnabled=1"
    PLEX_PREFERENCE_14: "CinemaTrailersFromLibrary=0"
    PLEX_PREFERENCE_15: "CinemaTrailersType=1"
    PLEX_PREFERENCE_16: "MetricsEpoch=1"
    PLEX_PREFERENCE_17: "AcceptedEULA=1"
    PLEX_PREFERENCE_18: "PublishServerOnPlexOnlineKey=1"
    PLEX_PREFERENCE_19: "DvrIncrementalEpgLoader=0"
    PLEX_PREFERENCE_20: "LastAutomaticMappedPort=0"
    PLEX_PREFERENCE_21: "DisableTLSv1_0=1"
    PLEX_PREFERENCE_22: "RelayEnabled=0"
    PLEX_PREFERENCE_23: "TreatWanIpAsLocal=0"
    PLEX_PREFERENCE_24: "customConnections=https://plex.cajun.pro"
    PLEX_PREFERENCE_25: "LanguageInCloud=1"
    PLEX_PREFERENCE_26: "GdmEnabled=0"
    PLEX_PREFERENCE_27: "secureConnections=2"
    PLEX_PREFERENCE_28: "TranscoderToneMapping=0"
  nodeSelector:
    cajun.pro/cluster-gen: "2"
  persistence:
    config:
      enabled: true
      nameSuffix: "-"
      storageClass: rook-ceph-block
      size: 50Gi
      accessMode: ReadWriteOnce
      skipuninstall: true
    transcode:
      enabled: true
      emptyDir:
        enabled: true
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
  probes:
    liveness:
      enabled: false
      custom: true
      spec:
        initialDelaySeconds: 60
        periodSeconds: 60
        exec:
          command:
            - cat
            - /tv/healthcheck
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4"
      nvidia.com/gpu: "1"
  additionalVolumes:
    - name: tv
      nfs:
        server: 10.0.10.211
        path: /mnt/media/tv
    - name: tv4k
      nfs:
        server: 10.0.10.211
        path: /mnt/media/tv4k
    - name: movies
      nfs:
        server: 10.0.10.211
        path: /mnt/media/movies
    - name: movies4k
      nfs:
        server: 10.0.10.211
        path: /mnt/media/movies4k
    - name: audiobooks
      nfs:
        server: 10.0.10.211
        path: /mnt/media/audiobooks
  additionalVolumeMounts:
    - mountPath: /mnt/media/tv
      name: tv
      readOnly: true
    - mountPath: /mnt/media/tv4k
      name: tv4k
      readOnly: true
    - mountPath: /mnt/media/movies
      name: movies
      readOnly: true
    - mountPath: /mnt/media/movies4k
      name: movies4k
      readOnly: true
    - mountPath: /mnt/media/audiobooks
      name: audiobooks
      readOnly: true
  ingress:
    enabled: true
    domainName: "cajun.pro"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - hostTpl: '{{ include "common.names.fullname" . }}.{{ .Values.ingress.domainName }}'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ include "common.names.fullname" . }}.{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ include "common.names.fullname" . }}-{{ .Values.ingress.domainName | replace "." "-" }}'
