global:
  fullnameOverride: plex
  domainName: "cajun.pro"

plex:
  image:
    repository: ghcr.io/k8s-at-home/plex
    tag: v1.25.0.5282-2edd3c44d
  env:
    # cat /config/Library/Application\ Support/Plex\ Media\ Server/Preferences.xml | tr " " "\n" | \
    # sed -n '/<Preferences/,$p' | tail -n +2 | sed 's,/>,,g' | \
    # sed '/\(OldestPreviousVersion\|MachineIdentifier\|^PlexOnline\|Certificate\|PubSub\|NeedsUpdate\)/d' | \
    # sed 's/"//g' | awk '{print "PLEX_PREFERENCE_"i++": \""$0"\""}'
    PLEX_PREFERENCE_0: "allowedNetworks=10.0.10.0/24,172.16.0.0/16"
    PLEX_PREFERENCE_1: "TranscoderTempDirectory=/transcode"
    PLEX_PREFERENCE_2: "FriendlyName=NickFlix"
    PLEX_PREFERENCE_3: "HardwareAcceleratedCodecs=1"
    PLEX_PREFERENCE_4: "autoEmptyTrash=1"
    PLEX_PREFERENCE_5: "ManualPortMappingPort=443"
    PLEX_PREFERENCE_6: "ScheduledLibraryUpdateInterval=86400"
    PLEX_PREFERENCE_7: "TranscoderCanOnlyRemuxVideo=0"
    PLEX_PREFERENCE_8: "HardwareAcceleratedEncoders=1"
    PLEX_PREFERENCE_9: "EnableIPv6=0"
    PLEX_PREFERENCE_10: "sendCrashReports=0"
    PLEX_PREFERENCE_11: "DlnaEnabled=0"
    PLEX_PREFERENCE_12: "ManualPortMappingMode=1"
    PLEX_PREFERENCE_13: "ScheduledLibraryUpdatesEnabled=1"
    PLEX_PREFERENCE_14: "CinemaTrailersFromLibrary=0"
    PLEX_PREFERENCE_15: "CinemaTrailersType=1"
    PLEX_PREFERENCE_16: "MetricsEpoch=1"
    PLEX_PREFERENCE_17: "AcceptedEULA=1"
    PLEX_PREFERENCE_18: "PublishServerOnPlexOnlineKey=1"
    PLEX_PREFERENCE_19: "DvrIncrementalEpgLoader=0"
    PLEX_PREFERENCE_20: "LastAutomaticMappedPort=0"
    PLEX_PREFERENCE_21: "DisableTLSv1_0=1"
    PLEX_PREFERENCE_22: "RelayEnabled=0"
    PLEX_PREFERENCE_23: "TreatWanIpAsLocal=0"
    PLEX_PREFERENCE_24: "customConnections=https://plex.cajun.pro"
    PLEX_PREFERENCE_25: "LanguageInCloud=1"
    PLEX_PREFERENCE_26: "GdmEnabled=0"
    PLEX_PREFERENCE_27: "secureConnections=2"
    PLEX_PREFERENCE_28: "TranscoderToneMapping=0"
  persistence:
    config:
      enabled: true
      nameOverride: "-"
      storageClass: cstor-replica-pool
      size: 100Gi
      accessMode: ReadWriteOnce
      retain: true
    transcode:
      enabled: true
      type: emptyDir
      mountPoint: /transcode
    tv:
      enabled: true
      type: custom
      mountPath: /mnt/media/tv
      readOnly: true
      volumeSpec:
        nfs:
          server: 10.0.10.211
          path: /mnt/media/tv
    tv4k:
      enabled: true
      type: custom
      mountPath: /mnt/media/tv4k
      readOnly: true
      volumeSpec:
        nfs:
          server: 10.0.10.211
          path: /mnt/media/tv4k
    movies:
      enabled: true
      type: custom
      mountPath: /mnt/media/movies
      readOnly: true
      volumeSpec:
        nfs:
          server: 10.0.10.211
          path: /mnt/media/movies
    movies4k:
      enabled: true
      type: custom
      mountPath: /mnt/media/movies4k
      readOnly: true
      volumeSpec:
        nfs:
          server: 10.0.10.211
          path: /mnt/media/movies4k
    audiobooks:
      enabled: true
      type: custom
      mountPath: /mnt/media/audiobooks
      readOnly: true
      volumeSpec:
        nfs:
          server: 10.0.10.211
          path: /mnt/media/audiobooks
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 500
  probes:
    liveness:
      enabled: false
      custom: true
      spec:
        initialDelaySeconds: 60
        periodSeconds: 60
        exec:
          command:
            - cat
            - /tv/healthcheck
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4"
      nvidia.com/gpu: "1"
  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - host: '{{ .Values.global.fullnameOverride }}.{{ .Values.global.domainName }}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.fullnameOverride }}.{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.fullnameOverride }}-{{ .Values.global.domainName | replace "." "-" }}'
