apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      restartPolicy: Always
      containers:
      - name: postgres
        image: postgres:9.5.15-alpine
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-env
        volumeMounts:
             - mountPath: /var/lib/postgresql/data
               name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres
