{{- if .Values.podDisruptionBudget.enabled -}}
  {{ $argoName := index .Values "argo-cd" "fullnameOverride" }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $argoName }}-repo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $argoName }}-repo-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- end }}

