apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: meta
spec:
  generators:
    - git:
        repoURL: https://github.com/DirtyCajunRice/GitOps-Argo-CD.git
        revision: refactor
        directories:
          - path: "cluster-critical"
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: cluster-critical
      source:
        path: '{{ path }}'
        targetRevision: refactor
        repoURL: https://github.com/DirtyCajunRice/GitOps-Argo-CD.git
      destination:
        namespace: argocd
        name: do
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=background
