apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: stripe
spec:
  pools:
    {{- range $node, $bd := .Values.nodes }}
    - nodeSelector:
        kubernetes.io/hostname: {{ printf "%s.k8s.cajun.pro" $node | quote }}
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: {{ printf "blockdevice-%s" $bd | quote }}
      poolConfig:
        dataRaidGroupType: "stripe"
    {{- end }}

