{
 "title": "OpenEBS Volume Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OpenEBS",
    "label": "OpenEBS Volume",
    "query": {
     "query": "label_values(openebs_size_of_volume, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Elapsed time since Volume was provisioned",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_uptime{container=\"maya-volume-exporter\", job=~\"$OpenEBS\"}/60"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "singlestat",
   "description": "Capacity Used by the Volume",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_size_of_volume{job=~\"$OpenEBS\"}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_actual_used{job=~\"$OpenEBS\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "description": "IOPS",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_reads{container=\"maya-volume-exporter\r\", job=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{ job }}"
    },
    {
     "expr": "increase(openebs_writes{container=\"maya-volume-exporter\", job=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Throughput",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_read_block_count{container=\"maya-volume-exporter\", job=~\"$OpenEBS\"}[1m])/(1024*1024*60)",
     "legendFormat": "{{ job }}"
    },
    {
     "expr": "increase(openebs_write_block_count{container=\"maya-volume-exporter\", job=~\"$OpenEBS\"}[1m])/(1024*1024*60)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Latency",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "((increase(openebs_read_time{container=\"maya-volume-exporter\", job=~\"$OpenEBS\"}[1m]))/(increase(openebs_reads{container=\"maya-volume-exporter\", job=~\"$OpenEBS\"}[1m])))/1000000",
     "legendFormat": "{{ job }}"
    },
    {
     "expr": "((increase(openebs_write_time{container=\"maya-volume-exporter\", job=~\"$OpenEBS\"}[1m]))/(increase(openebs_writes{container=\"maya-volume-exporter\", job=~\"$OpenEBS\"}[1m])))/1000000",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}