apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cstor-replica-pool
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  cstorPoolCluster: stripe
  replicaCount: '3'
