{{- range $app, $data := .Values.apps -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: cajun-pro
    name: home
  project: default
  source:
    chart: {{ $.Values.chart.name }}
    repoURL: {{ $.Values.chart.repoURL }}
    targetRevision: {{ $.Values.chart.revision }}
    helm:
      values: |-
        fullnameOverride: {{ $app }}
        image:
          registry: {{ $data.image.registry }}
          repository: {{ $data.image.repository }}
          tag: {{ $data.image.tag }}
        idea:
          config:
            path: "/config/config"
          system:
            path: "/config/system"
          plugins:
            path: "/config/plugins"
          log:
            path: "/config/plugins"
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: ingress-google-auth@kubernetescrd,cajun-pro-stripprefixregex@kubernetescrd
            traefik.ingress.kubernetes.io/router.priority: "10"
            {{- if eq $app "goland" }}
            cert-manager.io/cluster-issuer: le-production
            {{- end }}
          hosts:
            - host: {{ $.Values.domainName }}
              paths:
                - path: /{{ $app }}
                  pathType: Prefix
          tls:
            - hosts: [{{ $.Values.domainName }}]
              secretName: '{{ $.Values.domainName | replace "." "-" }}'
          additionalIngresses:
            - enabled: false
              nameSuffix: "api"
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
              hosts:
                - host: {{ $.Values.domainName }}
                  paths:
                    - path: /{{ $app }}/api
                      pathType: Prefix
              tls:
                - hosts: [{{ $.Values.domainName }}]
                  secretName: '{{ $.Values.domainName | replace "." "-" }}'
        persistence:
        {{- if eq $app "goland" }}
          config:
        {{- else }}
          data:
        {{- end }}
            enabled: true
            nameSuffix: "-"
            storageClass: rook-cephfs
            size: 10Gi
            accessMode: ReadWriteMany
            skipuninstall: true
        nodeSelector:
          cajun.pro/cluster-gen: "2"
        additionalVolumes:
          - name: ide-cajun-pro
            secret:
              secretName: ide-cajun-pro
        additionalVolumeMounts:
          - name: ide-cajun-pro
            mountPath: /tmp/certs
{{ end }}
