{{- range $app, $data := .Values.apps -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: cajun-pro
    name: home
  project: default
  source:
    chart: {{ $.Values.chart.name }}
    repoURL: {{ $.Values.chart.repoURL }}
    targetRevision: {{ $.Values.chart.revision }}
    helm:
      values: |-
        fullnameOverride: {{ $app }}
        image:
          registry: {{ $data.image.registry }}
          repository: {{ $data.image.repository }}
          tag: {{ $data.image.tag }}
        idea:
          config:
            path: "/config/config"
          system:
            path: "/config/system"
          plugins:
            path: "/config/plugins"
          log:
            path: "/config/plugins"
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: ingress-google-auth@kubernetescrd
            traefik.ingress.kubernetes.io/router.priority: "10"
            cert-manager.io/cluster-issuer: le-production
          hosts:
            - host: {{ printf "%s.%s" $app $.Values.domainName }}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts: [{{ printf "%s.%s" $app $.Values.domainName }}]
              secretName: '{{ printf "%s-%s" $app $.Values.domainName | replace "." "-" }}'
        persistence:
          config:
            enabled: true
            nameSuffix: "-"
            storageClass: rook-cephfs
            size: 10Gi
            accessMode: ReadWriteMany
            skipuninstall: true
        nodeSelector:
          cajun.pro/cluster-gen: "2"
        additionalVolumes:
          - name: {{ printf "%s-%s" $app $.Values.domainName | replace "." "-" }}
            secret:
              secretName: {{ printf "%s-%s" $app $.Values.domainName | replace "." "-" }}
        additionalVolumeMounts:
          - name: {{ printf "%s-%s" $app $.Values.domainName | replace "." "-" }}
            mountPath: /tmp/certs
        env:
          ORG_JETBRAINS_PROJECTOR_SERVER_SSL_PROPERTIES_PATH: /config/ssl.properties
        service:
          labels:
            traefik.ingress.kubernetes.io/service.serversscheme: https
{{ end }}
