{{- range $app, $data := .Values.apps -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: cajun-pro
    name: home
  project: default
  source:
    chart: {{ $.Values.chart.name }}
    repoURL: {{ $.Values.chart.repoURL }}
    targetRevision: {{ $.Values.chart.revision }}
    helm:
      values: |-
        fullnameOverride: {{ $app }}
        image:
          registry: "{{ default $.Values.defaultImage.registry $data.image.registry }}"
          repository: {{ $data.image.repository }}
          tag: "{{ default $.Values.defaultImage.tag $data.image.tag }}"
        idea:
          config:
            path: "/config"
          system:
            path: "/config/system"
          plugins:
            path: "/config/plugins"
          log:
            path: "/config/log"
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: ingress-google-auht-home@kubernetescrd
            traefik.ingress.kubernetes.io/router.priority: "10"
            cert-manager.io/cluster-issuer: le-production
          hosts:
            - host: "{{ printf "%s.%s" $app $.Values.domainName }}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts: ["{{ printf "%s.%s" $app $.Values.domainName }}"]
              secretName: '{{ printf "%s-%s" $app $.Values.domainName | replace "." "-" }}'
        persistence:
          config:
            enabled: true
            nameSuffix: "-"
            storageClass: rook-cephfs
            size: 10Gi
            accessMode: ReadWriteMany
            skipuninstall: true
        nodeSelector:
          cajun.pro/cluster-gen: "2"
        sslGen:
          enabled: true
          certs:
            secret: "{{ printf "%s-%s" $app $.Values.domainName | replace "." "-" }}"
        additionalVolumes:
          - name: git-data
            persistentVolumeClaim:
              claimName: git-data
          - name: jetbrains-projector-config
            persistentVolumeClaim:
              claimName: jetbrains-projector-config
        additionalVolumeMounts:
          - name: git-data
            mountPath: /git
          - name: jetbrains-projector-config
            mountPath: /config/JetBrains
        service:
          labels:
            traefik.ingress.kubernetes.io/service.serversscheme: https
{{ end }}
