raw:
  resources:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          helm.sh/resource-policy: keep
        name: jetbrains-projector-config
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 40Gi
        storageClassName: rook-cephfs
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          helm.sh/resource-policy: keep
        name: git-data
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
        storageClassName: rook-cephfs