spc:
  - APP_KEY
  - DISCORD_APP_ID
  - DISCORD_APP_SECRET
  - FACEBOOK_APP_ID
  - FACEBOOK_APP_SECRET
  - GITHUB_APP_ID
  - GITHUB_APP_SECRET
  - GITLAB_APP_ID
  - GITLAB_APP_SECRET
  - GOOGLE_APP_ID
  - GOOGLE_APP_SECRET
  - MAIL_FROM
  - MAIL_PASSWORD
  - MAIL_USERNAME
  - STORAGE_S3_BUCKET
  - STORAGE_S3_KEY
  - STORAGE_S3_SECRET
  - STORAGE_URL
  - db_password
  - db_username
  - mysql-config

bookstack:
  fullnameOverride: bookstack

  image:
    repository: ghcr.io/linuxserver/bookstack
    tag: version-v21.04.3

  replicas: 3
  envFrom:
    - secretRef:
        name: bookstack
  envValueFrom:
    DB_USERNAME:
      secretKeyRef:
        key: db_username
        name: bookstack
    DB_PASSWORD:
      secretKeyRef:
        key: db_password
        name: bookstack
  env:
    APP_URL: https://wiki.cajun.pro
    DB_HOST: mysql-bookstack-pods
    DB_DATABASE: bookstack_cajunpro
    MAIL_DRIVER: smtp
    MAIL_FROM_NAME: "cajun.pro Wiki"
    MAIL_HOST: smtp.gmail.com
    MAIL_PORT: "587"
    MAIL_ENCRYPTION: TLS
    APP_ENV: production
    APP_LANG: en
    APP_AUTO_LANG_PUBLIC: "true"
    DRAWIO: "true"
    APP_VIEWS_BOOKS: list
    APP_VIEWS_BOOKSHELVES: grid
    REVISION_LIMIT: "false"
    STORAGE_TYPE: s3
    STORAGE_S3_REGION: us-east-1
    CACHE_DRIVER: database
    SESSION_DRIVER: database
    ALLOW_ROBOTS: "false"
    ALLOW_CONTENT_SCRIPTS: "true"
    GOOGLE_SELECT_ACCOUNT: "true"
    GOOGLE_AUTO_REGISTER: "true"
    GOOGLE_AUTO_CONFIRM_EMAIL: "true"
    GITHUB_AUTO_REGISTER: "true"
    GITHUB_AUTO_CONFIRM_EMAIL: "true"
    GITLAB_BASE_URI: "false"
    GITLAB_AUTO_REGISTER: "true"
    GITLAB_AUTO_CONFIRM_EMAIL: "true"
    FACEBOOK_AUTO_REGISTER: "true"
    FACEBOOK_AUTO_CONFIRM_EMAIL: "true"
    DISCORD_AUTO_REGISTER: "true"
    DISCORD_AUTO_CONFIRM_EMAIL: "true"

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - host: wiki.cajun.pro
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: [wiki.cajun.pro]
        secretName: wiki-cajun-pro

  additionalVolumeMounts:
    - name: secrets
      mountPath: /mnt/secrets
      readOnly: true

  additionalVolumes:
    - name: secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: bookstack

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - bookstack
            topologyKey: kubernetes.io/hostname

  persistance:
    env:
      enabled: true
      emptyDir:
        enabled: true
      mountPath: /config/www/.env
      subPath: .env
