global:
  cluster: do
  fullnameOverride: bookstack

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/cajun-pro/bookstack
    secretObjects: true
    objects:
      - name: APP_KEY
      - name: DISCORD_APP_ID
      - name: DISCORD_APP_SECRET
      - name: FACEBOOK_APP_ID
      - name: FACEBOOK_APP_SECRET
      - name: GITHUB_APP_ID
      - name: GITHUB_APP_SECRET
      - name: GITLAB_APP_ID
      - name: GITLAB_APP_SECRET
      - name: GOOGLE_APP_ID
      - name: GOOGLE_APP_SECRET
      - name: MAIL_FROM
      - name: MAIL_PASSWORD
      - name: MAIL_USERNAME
      - name: STORAGE_S3_BUCKET
      - name: STORAGE_S3_KEY
      - name: STORAGE_S3_SECRET
      - name: STORAGE_URL
      - name: db_password
        secretName: password
      - name: db_username
        secretName: username
      - name: mysql-config
    extraSecretObjects:
      - type: Opaque
        secretName: mysql-bookstack-config
        data:
          - key: config.cnf
            objectName: mysql-config

bookstack:
  image:
    repository: ghcr.io/linuxserver/bookstack
    tag: version-v21.04.3

  replicas: 3

  envFrom:
    - secretRef:
        name: bookstack
  env:
    APP_URL: https://wiki.cajun.pro
    DB_HOST: $(MYSQL_BOOKSTACK_SERVICE_HOST)
    DB_DATABASE: bookstack_cajunpro
    MAIL_DRIVER: smtp
    MAIL_FROM_NAME: "cajun.pro Wiki"
    MAIL_HOST: smtp.gmail.com
    MAIL_PORT: "587"
    MAIL_ENCRYPTION: TLS
    APP_ENV: production
    APP_LANG: en
    APP_AUTO_LANG_PUBLIC: "true"
    DRAWIO: "true"
    APP_VIEWS_BOOKS: list
    APP_VIEWS_BOOKSHELVES: grid
    REVISION_LIMIT: "false"
    STORAGE_TYPE: s3
    STORAGE_S3_REGION: us-east-1
    CACHE_DRIVER: database
    SESSION_DRIVER: database
    ALLOW_ROBOTS: "false"
    ALLOW_CONTENT_SCRIPTS: "true"
    GOOGLE_SELECT_ACCOUNT: "true"
    GOOGLE_AUTO_REGISTER: "true"
    GOOGLE_AUTO_CONFIRM_EMAIL: "true"
    GITHUB_AUTO_REGISTER: "true"
    GITHUB_AUTO_CONFIRM_EMAIL: "true"
    GITLAB_BASE_URI: "false"
    GITLAB_AUTO_REGISTER: "true"
    GITLAB_AUTO_CONFIRM_EMAIL: "true"
    FACEBOOK_AUTO_REGISTER: "true"
    FACEBOOK_AUTO_CONFIRM_EMAIL: "true"
    DISCORD_AUTO_REGISTER: "true"
    DISCORD_AUTO_CONFIRM_EMAIL: "true"
    DB_PASSWORD:
      secretKeyRef:
        key: password
        name: bookstack
    DB_USERNAME:
      secretKeyRef:
        key: username
        name: bookstack

  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - host: wiki.cajun.pro
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: [wiki.cajun.pro]
          secretName: wiki-cajun-pro

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - bookstack
            topologyKey: kubernetes.io/hostname
  probes:
    liveness:
      spec:
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 30
  persistence:
    env:
      enabled: true
      type: emptyDir
      mountPath: /config/www/.env
      subPath: .env
    secrets:
      enabled: true
      type: custom
      mountPath: /mnt/secrets
      readOnly: true
      volumeSpec:
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: bookstack
