cluster: do

traefik:
  additionalArguments:
    - "--providers.kubernetesingress.ingressendpoint.hostname=do.traefik.k8s.cajun.pro"
    - "--entryPoints.websecure.proxyProtocol.trustedIPs=10.120.0.0/20"
    - "--entryPoints.web.proxyProtocol.trustedIPs=10.120.0.0/20"
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-name: traefik
      service.beta.kubernetes.io/do-loadbalancer-protocol: tcp
      service.beta.kubernetes.io/do-loadbalancer-size-slug: lb-small
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "2"
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "10"
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "3"
  pilot:
    token: "cac885fb-0bee-4b6e-a316-ceaf61cab202"
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
  logs:
    general:
      format: json
      level: INFO
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: 'app.kubernetes.io/name'
                  operator: In
                  values:
                    - traefik
            topologyKey: 'kubernetes.io/hostname'
