name: prometheus
apiVersion: v2
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 41.9.1
    repository: https://prometheus-community.github.io/helm-charts
    alias: kps
  - name: addons
    version: 1.0.0
    repository: file://../../addons
