kps:
  grafana:
    enabled: false

  alertmanager:
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      paths:
        - /
      hosts:
        - do.alertmanager.k8s.cajun.pro
      annotations:
        cert-manager.io/cluster-issuer: le-production
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik-outpost@kubernetescrd
      tls:
        - secretName: do-alertmanager-k8s-cajun-pro
          hosts:
            - do.alertmanager.k8s.cajun.pro

  prometheus:
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      hosts:
        - do.prometheus.k8s.cajun.pro
      paths:
        - /
      tls:
        - hosts: [do.prometheus.k8s.cajun.pro]
          secretName: do-prometheus-k8s-cajun-pro
      annotations:
        cert-manager.io/cluster-issuer: le-production
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik-outpost@kubernetescrd
