global:
  cluster: do
  domainName: images.cajun.pro

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/cajun-pro/xbackbone
    objects:
      - name: config.php

xbackbone:
  fullnameOverride: xbackbone

  image:
    repository: ghcr.io/itscontained/xbackbone
    tag: v3.3.5

  env:
    TZ: UTC
    APP_NAME: "images.cajun.pro"
    URL: "https://images.cajun.pro"
    PHP_UPLOAD_MAX_FILESIZE: "25G"

  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}'

  persistence:
    db:
      enabled: true
      nameOverride: "-"
      storageClass: do-block-storage
      size: 1Gi
      accessMode: ReadWriteOnce
      retain: true
      mountPath: /app/resources/database
    config:
      enabled: true
      type: emptyDir
      mountPath: /app/config
    secret:
      enabled: true
      type: custom
      volumeSpec:
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: xbackbone

  additionalVolumeMounts:
    - name: db
      mountPath: /app/storage
      subPath: storage

  # additionalVolumes:
  #   - name: secret
  #     csi:
  #       driver: secrets-store.csi.k8s.io
  #       readOnly: true
  #       volumeAttributes:
  #         secretProviderClass: xbackbone

  initContainers:
    cp:
      name: cp
      image: busybox:1.37
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - '-c'
        - 'cp /tmp/config.php /app/config/ && chown 1000:1000 /app/config/config.php'
      volumeMounts:
        - name: secret
          mountPath: /tmp/config.php
          subPath: config.php
          readOnly: true
        - mountPath: /app/config
          name: config
