xbackbone:
  fullnameOverride: xbackbone

  image:
    repository: ghcr.io/itscontained/xbackbone
    tag: v3.3.5

  env:
    TZ: UTC
    APP_NAME: "images.cajun.pro"
    URL: "https://images.cajun.pro"
    PHP_UPLOAD_MAX_FILESIZE: "25G"

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    domainName: images.cajun.pro
    hosts:
      - hostTpl: '{{ .Values.ingress.domainName }}'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.ingress.domainName | replace "." "-" }}'

  persistence:
    db:
      enabled: true
      nameSuffix: "-"
      storageClass: do-block-storage
      size: 1Gi
      accessMode: ReadWriteOnce
      skipuninstall: true
      mountPath: /app/resources/database
    config:
      enabled: true
      emptyDir:
        enabled: true
      mountPath: /app/config

  additionalVolumeMounts:
    - name: db
      mountPath: /app/storage
      subPath: storage

  additionalVolumes:
    - name: secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: xbackbone

  initContainers:
    - command:
        - /bin/sh
        - '-c'
        - if [ ! -f /appcp /tmp/config.php /app/config/ && chown 1000:1000 /app/config/config.php'
      image: busybox:1.28
      imagePullPolicy: IfNotPresent
      name: cp
      volumeMounts:
        - name: secret
          mountPath: /tmp/config.php
          subPath: config.php
          readOnly: true
        - mountPath: /app/config
          name: config
