kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-b0d01ab4-a8d5-4ff3-9cd7-1cac76944559
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=&oem=esse&user=5a971086-a478-11eb-a2c5-c24e499c7467&b=true&s=%2Fdev%2Fsdb&c=px-cluster-b0d01ab4-a8d5-4ff3-9cd7-1cac76944559&stork=true&csi=true&lh=true&mon=true&st=vault&promop=true"
    portworx.io/misc-args: "--oem esse"
spec:
  image: portworx/oci-monitor:2.7.0
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    devices:
      - /dev/sdb
  secretsProvider: vault
  stork:
    enabled: true
    args:
      webhook-controller: "false"
  userInterface:
    enabled: true
  autopilot:
    enabled: true
  monitoring:
    prometheus:
      enabled: true
      exportMetrics: true
  featureGates:
    CSI: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: px-essential
data:
  px-essen-user-id: NWE5NzEwODYtYTQ3OC0xMWViLWEyYzUtYzI0ZTQ5OWM3NDY3
  px-osb-endpoint: aHR0cHM6Ly9weGVzc2VudGlhbHMucG9ydHdvcnguY29tL29zYi9iaWxsaW5nL3YxL3JlZ2lzdGVy
