apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-do
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: monitoring
    name: do
  project: default
  source:
    path: prometheus
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-do.yaml
      values: |
        cluster: do
    repoURL: git@github.com:DirtyCajunRice/GitOps-Argo-CD.git
#  syncPolicy:
#    automated: {}
