---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  annotations:
    metallb.universe.tf/allow-shared-ip: torrent
spec:
  ports:
  - port: 8384
    targetPort: 8384
    protocol: TCP
    name: http
  - port: 22000
    targetPort: 22000
    protocol: TCP
    name: bittorrent
  selector:
    app: syncthing
  type: LoadBalancer
  loadBalancerIP: 10.0.10.150
