apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rtorrent
  labels:
    app: rtorrent
spec:
  selector:
    matchLabels:
      app: rtorrent
  endpoints:
  - port: metrics

