name: external-dns
apiVersion: v2
version: 1.0.0
dependencies:
  - name: external-dns
    version: 5.0.0
    # renovatebot:alturl=https://github.com/bitnami/charts/tree/master/bitnami/external-dns
    repository: https://charts.bitnami.com/bitnami
