global:
  cluster: ""

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/external/aws
    objects:
      - name: credentials

external-dns:
  fullnameOverride: external-dns

  image:
    registry: docker.io
    repository: bitnami/external-dns
    # renovatebot:alturl=https://github.com/bitnami/bitnami-docker-external-dns
    tag: 0.9.0-debian-10-r9

  sources:
    - crd
    - service
    - ingress
  provider: aws

  aws:
    evaluateTargetHealth: false

  interval: "5m"
  logLevel: debug
  logFormat: json
  txtPrefix: "_."
  replicas: 1

  crd:
    create: true

  metrics:
    serviceMonitor:
      enabled: true

  extraEnv:
    - name: AWS_SHARED_CREDENTIALS_FILE
      value: /.aws/credentials

  extraVolumeMounts:
    - name: credentials
      mountPath: /.aws
      readOnly: true

