apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
spec:
  backendType: vault
  vaultMountPoint: kubernetes-home
  vaultRole: vault-auth
  data:
    - name: google_oauth_client_id
      key: kv-v2/data/auth/grafana
      property: google_oauth_client_id
    - name: google_oauth_client_secret
      key: kv-v2/data/auth/grafana
      property: google_oauth_client_secret
