apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-wc-synology
spec:
  schedule: "0 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync
              image: kroniak/ssh-client:3.10
              imagePullPolicy: IfNotPresent
              command: ["bash", "-c"]
              args:
                - cd /root &&
                  cp -r .ssh2 .ssh &&
                  chmod 700 -R .ssh &&
                  ls && ls .ssh2 && ls .ssh &&
                  scp -o StrictHostKeyChecking=no certs/* scp-sync@192.168.75.25:/volume1/certs
              volumeMounts:
                - mountPath: /root/certs
                  name: certs
                  readOnly: true
                - name: ssh
                  mountPath: /root/.ssh2
                  readOnly: true

          hostNetwork: true
          restartPolicy: OnFailure
          volumes:
            - name: certs
              secret:
                secretName: wc-home-cajun-pro
            - name: ssh
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: synology

