apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: synology
  namespace: cajun-pro
spec:
  provider: vault
  parameters:
    roleName: csi-secrets-store
    vaultAddress: https://vault.cajun.pro
    vaultKubernetesMountPath: kubernetes/home
    objects: |
      - objectName: id_rsa
        secretKey: id_rsa
        secretPath: kv-v2/data/k8s/cajun-pro/synology

