global:
  domainName: "nickflix.io"

organizr:
  fullnameOverride: organizr
  enableServiceLinks: false
  env:
    fpm: "true"
    branch: "v2-develop"
  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "5"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
              - path: /
                pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}'
  persistence:
    config:
      enabled: true
      nameOverride: "-"
      storageClass: cstor-replica-pool
      size: 3Gi
      accessMode: ReadWriteOnce
      retain: true
  resources:
    requests:
      cpu: 100m
      memory: 128m
