organizr:
  fullnameOverride: organizr
  enableServiceLinks: false
  env:
    fpm: "true"
    branch: "v2-develop"
  ingress:
    enabled: true
    domainName: "nickflix.io"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "5"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - hostTpl: '{{ .Values.ingress.domainName }}'
        paths:
            - path: /
              pathType: Prefix
    tls:
      - hostsTpl: ['{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.ingress.domainName | replace "." "-" }}'
  persistence:
    config:
      enabled: true
      nameSuffix: "-"
      storageClass: rook-ceph-block
      size: 1Gi
      accessMode: ReadWriteOnce
      skipuninstall: true
  nodeSelector:
    cajun.pro/cluster-gen: "2"
  resources:
    requests:
      cpu: 100m
      memory: 128m
