{{- $domain := "nickflix.io" -}}
{{- if eq .Values.env.TEMPLATE_NAME "l7-dark" -}}
  {{- $domain = "cajun.pro" -}}
{{- end -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "wc-%s" (replace "." "-" $domain) }}
spec:
  dnsNames:
    - {{ printf "*.%s" $domain | quote }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: le-production
  secretName: {{ printf "wc-%s" (replace "." "-" $domain) }}

