apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wc-cajun-pro
spec:
  dnsNames:
    - "*.cajun.pro"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: le-production
  secretName: wc-cajun-pro

