{{- $theme := .Values.env.TEMPLATE_NAME -}}
{{- if eq .Release.Name "error-pages-home" -}}
  {{- $theme = "shuffle" -}}
{{- end -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: error-pages
spec:
  errors:
    status:
      - "400-599"
    query: /{{ $theme }}/{status}.html
    service:
      name: error-pages
      port: 8080
