applicationset:
  fullnameOverride: applicationset
  image:
    repository: quay.io/argoproj/argocd-applicationset
    tag: v0.2.0

  args:
    policy: create-update

  securityContext:
    fsGroup: 1000
