Unable to save changes: application spec is invalid: InvalidSpecError: Unable to generate manifests in plex: rpc error: code = Unknown desc = `helm template . --name-template plex --namespace cajun-pro --values values.yaml --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions ceph.rook.io/v1 --api-versions crd.projectcalico.org/v1 --api-versions kubernetes-client.io/v1 --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1alpha1 --api-versions nvidia.com/v1 --api-versions appcatalog.appscode.com/v1alpha1 --api-versions catalog.kubedb.com/v1alpha1 --api-versions externaldns.k8s.io/v1alpha1 --api-versions kubedb.com/v1alpha1 --api-versions mutators.kubedb.com/v1alpha1 --api-versions objectbucket.io/v1alpha1 --api-versions traefik.containo.us/v1alpha1 --api-versions validators.kubedb.com/v1alpha1 --api-versions acme.cert-manager.io/v1alpha3 --api-versions acme.cert-manager.io/v1alpha2 --api-versions cert-manager.io/v1alpha3 --api-versions cert-manager.io/v1alpha2 --api-versions rook.io/v1alpha2 --api-versions metrics.k8s.io/v1beta1 --include-crds` failed exit status 1: Error: template: plex/charts/plex/templates/common.yaml:1:3: executing "plex/charts/plex/templates/common.yaml" at <include "common.all" .>: error calling include: template: plex/charts/plex/charts/common/templates/_all.tpl:40:5: executing "common.all" at <include "common.ingress" .>: error calling include: template: plex/charts/plex/charts/common/templates/_ingress.tpl:12:8: executing "common.ingress" at <include "common.classes.ingress" .>: error calling include: template: plex/charts/plex/charts/common/templates/classes/_ingress.tpl:61:21: executing "common.classes.ingress" at <.path>: can't evaluate field path in type interface {} Use --debug flag to render out invalid YAML
plex:
  # hostNetwork: true
  controllerType: deployment
  fullnameOverride: plex
  env:
    ALLOWED_NETWORKS: "10.0.10.0/24,172.16.0.0/16"
    PLEX_PREFERENCE_1: "FriendlyName=NickFlix"
    PLEX_PREFERENCE_2: "EnableIPv6=0"
    PLEX_PREFERENCE_3: "sendCrashReports=0"
    # PLEX_PREFERENCE_4: "ManualPortMappingMode=1"
    # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"
    # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"
    # PLEX_PREFERENCE_6: "TranscoderQuality=2"
    # PLEX_PREFERENCE_7: "TreatWanIpAsLocal=0"
    # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"
  persistence:
    config:
      enabled: true
      storageClassName: rook-cephfs
      accessMode: ReadWriteMany
      size: 400Gi
      skipuninstall: true
  probes:
    liveness:
      enabled: true
      custom: true
      spec:
        initialDelaySeconds: 60
        periodSeconds: 60
        exec:
          command:
            - cat
            - /tv/healthcheck
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4"
      nvidia.com/gpu: "1"
  additionalVolumes:
    - name: tv
      nfs:
        server: 10.0.10.211
        path: /mnt/media/tv
    - name: tv4k
      nfs:
        server: 10.0.10.211
        path: /mnt/media/tv4k
    - name: movies
      nfs:
        server: 10.0.10.211
        path: /mnt/media/movies
    - name: movies4k
      nfs:
        server: 10.0.10.211
        path: /mnt/media/movies4k
    - name: audiobooks
      nfs:
        server: 10.0.10.211
        path: /mnt/media/audiobooks
  additionalVolumeMounts:
    - mountPath: /tv
      name: tv
      readOnly: true
    - mountPath: /tv4k
      name: tv4k
      readOnly: true
    - mountPath: /movies
      name: movies
      readOnly: true
    - mountPath: /movies4k
      name: movies4k
      readOnly: true
    - mountPath: /audiobooks
      name: audiobooks
      readOnly: true
  ingress:
    enabled: true
    domainName: "cajun.pro"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - hostTpl: '{{ .Values.fullnameOverride }}.{{ .Values.ingress.domainName }}'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hostTpl: ['{{ .Values.fullnameOverride }}.{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.fullnameOverride }}-{{ .Values.ingress.domainName | replace "." "-" }}'
        secretName: plex-cajun-pro
