plex:
  # hostNetwork: true
  controllerType: deployment
  fullnameOverride: plex
  env:
    ALLOWED_NETWORKS: "10.0.10.0/24,172.16.0.0/16"
    PLEX_PREFERENCE_1: "FriendlyName=NickFlix"
    PLEX_PREFERENCE_2: "EnableIPv6=0"
    PLEX_PREFERENCE_3: "sendCrashReports=0"
    PLEX_PREFERENCE_4: "DlnaEnabled=0"
    PLEX_PREFERENCE_5: "ManualPortMappingMode=1"
    PLEX_PREFERENCE_6: "ManualPortMappingPort=443"
    PLEX_PREFERENCE_7: "ScheduledLibraryUpdatesEnabled=1"
    PLEX_PREFERENCE_8: "CinemaTrailersFromLibrary=0"
    PLEX_PREFERENCE_9: "CinemaTrailersType=1"
    PLEX_PREFERENCE_10: "customConnections=https://plex.cajun.pro"
    PLEX_PREFERENCE_11: "HardwareAcceleratedCodecs=1"
    PLEX_PREFERENCE_12: "autoEmptyTrash=1"
    PLEX_PREFERENCE_13: "TranscoderTempDirectory=/transcode"
    PLEX_PREFERENCE_14: "ScheduledLibraryUpdateInterval=86400"
    PLEX_PREFERENCE_15: "TranscoderCanOnlyRemuxVideo=1"
    PLEX_PREFERENCE_16: "HardwareAcceleratedEncoders=1"
    PLEX_PREFERENCE_17: "DisableTLSv1_0=1"
    PLEX_PREFERENCE_18: "RelayEnabled=0"
    PLEX_PREFERENCE_19: "TreatWanIpAsLocal=0"
    PLEX_PREFERENCE_20: "GdmEnabled=0"
    PLEX_PREFERENCE_21: "secureConnections=2"
  nodeSelector:
    cajun.pro/cluster-gen: "2"
  persistence:
    config:
      enabled: true
      existingClaim: plex
      skipuninstall: true
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
  probes:
    liveness:
      enabled: true
      custom: true
      spec:
        initialDelaySeconds: 60
        periodSeconds: 60
        exec:
          command:
            - cat
            - /tv/healthcheck
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4"
#      nvidia.com/gpu: "1"
  additionalVolumes:
    - name: tv
      nfs:
        server: 10.0.10.211
        path: /mnt/media/tv
    - name: tv4k
      nfs:
        server: 10.0.10.211
        path: /mnt/media/tv4k
    - name: movies
      nfs:
        server: 10.0.10.211
        path: /mnt/media/movies
    - name: movies4k
      nfs:
        server: 10.0.10.211
        path: /mnt/media/movies4k
    - name: audiobooks
      nfs:
        server: 10.0.10.211
        path: /mnt/media/audiobooks
  additionalVolumeMounts:
    - mountPath: /tv
      name: tv
      readOnly: true
    - mountPath: /tv4k
      name: tv4k
      readOnly: true
    - mountPath: /movies
      name: movies
      readOnly: true
    - mountPath: /movies4k
      name: movies4k
      readOnly: true
    - mountPath: /audiobooks
      name: audiobooks
      readOnly: true
  ingress:
    enabled: true
    domainName: "cajun.pro"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - hostTpl: '{{ include "common.names.fullname" . }}.{{ .Values.ingress.domainName }}'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ include "common.names.fullname" . }}.{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ include "common.names.fullname" . }}-{{ .Values.ingress.domainName | replace "." "-" }}'
