apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.10-20210318
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
  monitoring:
    rulesNamespace: rook-ceph
  cleanupPolicy: {}
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cajun.pro/cluster-gen
              operator: In
              values:
              - "2"
  resources:
    osd:
      requests:
        memory: "2Gi"
      limits:
        memory: "4Gi"
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    useAllDevices: false
    deviceFilter: "sdb"
    nodes:
    - name: "node5.k8s.cajun.pro"
    - name: "node6.k8s.cajun.pro"
    - name: "node7.k8s.cajun.pro"
  disruptionManagement:
    osdMaintenanceTimeout: 30
    machineDisruptionBudgetNamespace: openshift-machine-api
