apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  cephVersion:
    # allowUnsupported: false
    image: ceph/ceph:v16.2.0-20210401

  dataDirHostPath: /var/lib/rook

  waitTimeoutForHealthyOSDInMinutes: 10

  dashboard:
    enabled: true

  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    # manageMachineDisruptionBudgets: false
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    # pgHealthCheckTimeout: 0

  healthCheck:
    daemonHealth:
      mon:
        # disabled: false
        interval: 45s
      osd:
        # disabled: false
        interval: 1m0s
      status:
        # disabled: false
        interval: 1m0s
    livenessProbe:
      mon: {}
        # disabled: false
      mgr: {}
        # disabled: false
      osd: {}
        # disabled: false

  mon:
    count: 3
    # allowMultiplePerNode: false

  mgr:
    count: 1
    modules:
      - name: pg_autoscaler
        enabled: true

  monitoring:
    enabled: true
    rulesNamespace: rook-ceph

  removeOSDsIfOutAndSafeToRemove: true
  network: {}
  cleanupPolicy:
    # allowUninstallWithVolumes: false
    # confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
  # continueUpgradeAfterChecksEvenIfNotHealthy: false
  # skipUpgradeChecks: false
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cajun.pro/cluster-gen
              operator: In
              values:
              - "2"
  resources:
    osd:
      requests:
        memory: "2Gi"
      limits:
        memory: "4Gi"

  storage:
    deviceFilter: "sdb"
    nodes:
      - name: "node5.k8s.cajun.pro"
      - name: "node6.k8s.cajun.pro"
      - name: "node7.k8s.cajun.pro"
    useAllDevices: false
    # useAllNodes: false
