statping:
  image:
    tag: v0.90.74
  fullnameOverride: statping
  persistence:
    data:
      enabled: false
  enableServiceLinks: false
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    subDomainName: "status"
    domainName: "cajun.pro"
    hosts:
      - hostTpl: '{{ .Values.ingress.subDomainName }}.{{ .Values.ingress.domainName }}'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ .Values.ingress.subDomainName }}.{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.ingress.subDomainName }}-{{ .Values.ingress.domainName | replace "." "-" }}'
  env:
    NAME: cajun.pro status
    DESCRIPTION: cajun.pro hosting status page
    VIRTUAL_HOST: https://status.cajun.pro
    DB_CONN: postgres
    DB_HOST: postgres-statping
    DB_DATABASE: postgres
    DB_USER: ~
    DB_PASS: ~
  envFrom:
    - secretRef:
        name: statping
  resources:
    requests:
     cpu: 100m
     memory: 128Mi
  postgresql:
    enabled: false
