flood:
  image:
    repository: jesec/flood
    tag: 4.5.4

  env:
    FLOOD_OPTION_rundir: /data
    FLOOD_OPTION_auth: none

  ingress:
    enabled: true
    domainName: "nickflix.io"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-0@kubernetescrd,cajun-pro-redirectregex@kubernetescrd
    hosts:
      - hostTpl: '{{ .Values.ingress.domainName }}'
        paths:
          - pathTpl: '{{ printf "/flood/%s" .Values.ingress.iteration }}'
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.ingress.domainName | replace "." "-" }}'

  persistence:
    data:
      enabled: true
      nameSuffix: "-"
      mountPath: /data
      storageClass: nfs-client
      accessMode: ReadWriteMany
      size: 1Gi
      skipuninstall: true

  nodeSelector:
    kubernetes.io/hostname: node4.k8s.cajun.pro

  resources:
    requests:
      cpu: 100m
      memory: 128m


