flood:
  fullnameOverride: flood

  image:
    repository: jesec/flood
    tag: 4.5.3


  # Other environment variables that can be configure can be seen at
  # https://github.com/jesec/flood/blob/master/config.cli.js
  env:
    FLOOD_OPTION_RUNDIR: /data
    FLOOD_OPTION_BASE_URI: /flood/1
    FLOOD_OPTION_RTHOST: rtorrent1
    FLOOD_OPTION_RTPORT: "5000"

  ingress:
    enabled: true
    domainName: "nickflix.io"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-0@kubernetescrd,cajun-pro-redirectslashwithstrip@kubernetescrd
    hosts:
      - hostTpl: '{{ .Values.ingress.domainName }}'
        paths:
          - path: /flood/1
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.ingress.domainName | replace "." "-" }}'

  persistence:
    data:
      enabled: true
      nameSuffix: "-"
      emptyDir:
        enabled: false
      mountPath: /data
      storageClass: nfs-client
      accessMode: ReadWriteMany
      size: 1Gi
      skipuninstall: true

  additionalVolumes:
    - mountPath: /config
      name: config
    - mountPath: /mnt
      name: media

  additionalVolumeMounts:
    - name: config
      hostPath:
        path: /mnt/nfs/rtorrent
        type: Directory
    - name: media
      hostPath:
        path: /mnt/media
        type: Directory

  nodeSelector:
    kubernetes.io/hostname: node4.k8s.cajun.pro

  resources:
    requests:
      cpu: 100m
      memory: 128m


