global:
  domainName: nickflix.io

flood:
  image:
    repository: jesec/flood
    tag: 4.6.1

  env:
    FLOOD_OPTION_rundir: /data
    FLOOD_OPTION_auth: none

  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-0@kubernetescrd,cajun-pro-redirectregex@kubernetescrd
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: '{{ printf "/flood/%s" .Values.global.iteration }}'
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}'

  persistence:
    data:
      enabled: false
      nameSuffix: "-"


  tolerations:
    - key: role
      value: storage
      effect: NoSchedule

  nodeSelector:
    node-role.kubernetes.io/storage: ""

  resources:
    requests:
      cpu: 100m
      memory: 128m

  additionalVolumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /mnt
      name: media
    - mountPath: /data
      name: data
