apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: overseerr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nickflix.io`) && PathPrefix(`/overseerr`)
      priority: 10
      middlewares:
        - name: stripprefixregex
      services:
        - kind: Service
          name: overseerr
          port: 5055
    - kind: Rule
      match: Host(`nickflix.io`) && HeadersRegexp(`Referer`, `{referer:https://nickflix.io/overseer/.*}`)
      priority: 15
      services:
        - kind: Service
          name: overseerr
          port: 5055
  tls:
    secretName: nickflix-io
