apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: overseerr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nickflix.io`) && PathPrefix(`/overseerr`)
      priority: 10
      middlewares:
        - name: strip-prefix-overseerr
        - name: overseerr-header
      services:
        - kind: Service
          name: overseerr
          port: 5055
    - kind: Rule
      match: Host(`nickflix.io`) && Headers(`X-Powered-By`, `Overseerr`) && Path(`/login`)
      priority: 15
      middlewares:
        - name: overseerr-redirectregex
        - name: overseerr-header2
      services:
        - kind: Service
          name: overseerr
          port: 5055
    - kind: Rule
      match: Host(`nickflix.io`) && Headers(`X-Powered-By`, `Overseerr`)
      priority: 20
      middlewares:
        - name: strip-prefix-overseerr
        - name: overseerr-header
      services:
        - kind: Service
          name: overseerr
          port: 5055
  tls:
    secretName: nickflix-io
