apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: overseerr-redirectregex
spec:
  redirectRegex:
    regex: ^https://nickflix.io/(.*)
    replacement: https://mydomain/overseerr/${1}
