apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: overseerr-rewritebody
spec:
  plugin:
    plugin-rewritebody:
      lastModified: true
      rewrites:
        - regex: 'href'
          replacement: 'testhehe'
