apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-critical
spec:
  generators:
    - git:
        repoURL: https://github.com/dirtycajunrice/gitops.git
        revision: HEAD
        files:
          - path: "cluster-critical/**/gen-config.json"
  template:
    metadata:
      name: '{{ name }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '/{{ path }}'
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: cluster-critical
      source:
        path: '{{ path }}'
        targetRevision: HEAD
        repoURL: https://github.com/dirtycajunrice/gitops.git
        helm:
          valueFiles:
            - values.yaml
            - '{{ valueFile }}'
      destination:
        namespace: '{{ namespace }}'
        name: '{{ cluster }}'
      syncPolicy:
        #  automated: {}
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=orphan
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: kopia-tls-cert
          jsonPointers:
            - /data
        - group: ""
          kind: Secret
          name: kopia-tls-key
          jsonPointers:
            - /data
