apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sonarr.fullnameOverride }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
