kube-prometheus-stack:
  fullnameOverride: prometheus
  alertmanager:
    fullnameOverride: alertmanager
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-google-auth@kubernetescrd
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - alertmanager.cajun.pro
      paths:
        - /
      tls:
        - secretName: alertmanager-cajun-pro
          hosts:
            - alertmanager.cajun.pro
  grafana:
    fullnameOverride: grafana
    testFramework:
      enabled: false
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - grafana.cajun.pro
      tls:
        - hosts:
            - grafana.cajun.pro
          secretName: grafana-cajun-pro
    nodeSelector:
      cajun.pro/cluster-gen: "2"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteMany
    plugins:
      - grafana-piechart-panel
    grafana.ini:
      server:
        root_url: https://grafana.cajun.pro
      auth.google:
        enabled: true
        scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
        auth_url: https://accounts.google.com/o/oauth2/auth
        token_url: https://accounts.google.com/o/oauth2/token
        allowed_domains: cajun.pro
    envValueFrom:
      GF_AUTH_GOOGLE_CLIENT_ID:
        secretKeyRef:
          key: google_oauth_client_id
          name: grafana-oauth
      GF_AUTH_GOOGLE_CLIENT_SECRET:
        secretKeyRef:
          key: google_oauth_client_secret
          name: grafana-oauth
  kubeScheduler:
    service:
      port: 10259
      targetPort: 10259
    serviceMonitor:
      https: true
      insecureSkipVerify: true
  kubeControllerManager:
    service:
      port: 10257
      targetPort: 10257
    serviceMonitor:
      https: true
      insecureSkipVerify: true
  kubeEtcd:
    service:
      port: 2381
      targetPort: 2381
  prometheusOperator:
    admissionWebhooks:
      failurePolicy: Ignore
  prometheus:
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-google-auth@kubernetescrd
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - prometheus.cajun.pro
      paths:
        - /
      tls:
        - hosts: [prometheus.cajun.pro]
          secretName: prometheus-cajun-pro
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
  kube-state-metrics:
    fullnameOverride: kube-state-metrics
  prometheus-node-exporter:
    fullnameOverride: node-exporter
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
