kube-prometheus-stack:
  alertmanager:
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: ingress-google-auth-home@kubernetescrd
      hosts:
        - alertmanager.cajun.pro
      paths:
        - /
      tls:
        - secretName: alertmanager-cajun-pro
          hosts:
            - alertmanager.cajun.pro
  grafana:
    fullnameOverride: grafana
    image:
      repository: grafana/grafana
      tag: 7.5.3
      pullPolicy: IfNotPresent
    testFramework:
      enabled: false
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - grafana.cajun.pro
      tls:
        - hosts:
            - grafana.cajun.pro
          secretName: grafana-cajun-pro
    nodeSelector:
      cajun.pro/cluster-gen: "2"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteMany
    plugins:
      - grafana-piechart-panel
    grafana.ini:
      server:
        root_url: https://grafana.cajun.pro
      auth.google:
        enabled: true
        scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
        auth_url: https://accounts.google.com/o/oauth2/auth
        token_url: https://accounts.google.com/o/oauth2/token
        allowed_domains: cajun.pro
    envValueFrom:
      GF_AUTH_GOOGLE_CLIENT_ID:
        secretKeyRef:
          key: google_oauth_client_id
          name: grafana-oauth
      GF_AUTH_GOOGLE_CLIENT_SECRET:
        secretKeyRef:
          key: google_oauth_client_secret
          name: grafana-oauth
  prometheus:
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: ingress-google-auth-home@kubernetescrd
      hosts:
        - prometheus.cajun.pro
      paths:
        - /
      tls:
        - hosts: [prometheus.cajun.pro]
          secretName: prometheus-cajun-pro
