apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: discord
spec:
  backendType: vault
  vaultMountPoint: kubernetes-do
  vaultRole: vault-auth
  data:
    - name: varken-bot-token
      key: kv-v2/data/auth/discord
      property: varken-bot-token