name: auto-voice-channels
apiVersion: v2
version: 1.0.0
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.0.0
  - name: addons
    version: 1.0.0
    repository: file://../../addons
