global:
  cluster: do

addons:
  spc:
    enabled: true
    defaultObjectPath: auth/auto-voice-channels
    objects:
      - name: config.json

image:
  repository: ghcr.io/itscontained/auto-voice-channels
  pullPolicy: Always
  tag: af2bc36a

strategy:
  type: Recreate

service:
  main:
    enabled: false

persistence:
  data:
    enabled: true
    nameOverride: "-"
    storageClass: do-block-storage
    size: 1Gi
    accessMode: ReadWriteOnce
    mountPath: /app/guilds
    skipuninstall: true
  config:
    enabled: true
    type: custom
    mountPath: /app/config.json
    subPath: config.json
    readOnly: true
    volumeSpec:
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: auto-voice-channels

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
