apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: mysql-seafile
spec:
  version: 8.0.23-v1
  storageType: Durable
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          app: seafile
        interval: 10s
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
  terminationPolicy: DoNotTerminate
