sonarr:
  image:
    repository: itscontained/sonarr
    tag: 3.0.5.1143
  env:
    TZ: America/Chicago
    PUID: "1000"
    PGID: "1000"
  ingress:
    enabled: true
    domainName: "nickflix.io"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-4@kubernetescrd
    tls:
      - hostsTpl: ['{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.ingress.domainName | replace "." "-" }}'
  persistence:
    config:
      enabled: true
      skipuninstall: true
  additionalVolumes:
    - name: mnt
      nfs:
        server: 10.0.10.211
        path: /mnt/media
    - name: emptydir
      emptyDir: {}
  additionalVolumeMounts:
    - name: mnt
      mountPath: /mnt/media
    - name: emptydir
      mountPath: /mnt/media/torrents/incomplete
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
#    fsGroup: 1000
  nodeSelector:
    cajun.pro/cluster-gen: "2"

