apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-home
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: monitoring
    name: home
  project: default
  source:
    path: prometheus
    targetRevision: HEAD
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
        - values.yaml
        - home.yaml
    repoURL: git@github.com:DirtyCajunRice/GitOps-Argo-CD.git
#  syncPolicy:
#    automated: {}
