global:
  cluster: home

traefik:
  additionalArguments:
    - "--providers.kubernetesingress.ingressendpoint.hostname=traefik-home.k8s.cajun.pro"
    - "--providers.kubernetesingress.ingressendpoint.ip=12.161.64.36"
    - "--experimental.plugins.plugin-rewritebody.modulename=github.com/traefik/plugin-rewritebody"
    - "--experimental.plugins.plugin-rewritebody.version=v0.3.1"
  service:
    externalIPs:
      - 172.30.0.10
  nodeSelector:
    cajun.pro/cluster-gen: "2"
  pilot:
    token: "23f45ed9-8bcb-43a5-b41f-1af0762be61d"
tfa:
  authHost: nickflix.io
  ingress:
    hosts:
      - host: nickflix.io
        paths: [/_oauth]
    tls:
      - hosts: [nickflix.io]
        secretName: nickflix-io
  nodeSelector:
    cajun.pro/cluster-gen: "2"
