apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mysql-bookstack-config
spec:
  backendType: vault
  vaultMountPoint: kubernetes-do
  vaultRole: vault-auth
  data:
    - name: config.cnf
      key: kv-v2/data/auth/bookstack
      property: mysql-config
