qbittorrent:
  image:
    repository: ghcr.io/k8s-at-home/qbittorrent
    pullPolicy: IfNotPresent
    tag: v4.3.4.1

  strategy:
    type: Recreate

  env:
    TZ: UTC

  service:
    port:
      port: 8080

  ingress:
    enabled: true
    domainName: nickflix.io
    app: radarr
    quality: 1080p
    iteration: ''
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-quadruple-strip-prefix@kubernetescrd
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      external-dns.alpha.kubernetes.io/hostname: ""
    hosts:
      - hostTpl: '{{ .Values.ingress.domainName }}'
        paths:
          - pathTpl: '{{ printf "/torrents/%s/%s/%v" .Values.ingress.app .Values.ingress.quality .Values.ingress.iteration }}'
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.ingress.domainName | replace "." "-" }}'
  tolerations:
    - key: role
      value: storage
      effect: NoSchedule

  nodeSelector:
    node-role.kubernetes.io/storage: ""

  hostPathMounts:
    config:
      enabled: true
      mountPath: /config
      hostPath: /tmp/placeholder
    incomplete:
      enabled: true
      setPermissions: false
      mountPath: /mnt/media/torrents/incomplete/radarr
      hostPath: /mnt/media/torrents/incomplete/radarr
    completed:
      enabled: true
      setPermissions: false
      mountPath: /mnt/media/torrents/completed/radarr
      hostPath: /mnt/media/torrents/completed/radarr

  podSecurityContext:
    # kah user
    runAsUser: 568
    # media group
    runAsGroup: 500
