qbittorrent:
  image:
    repository: ghcr.io/k8s-at-home/qbittorrent
    pullPolicy: IfNotPresent
    tag: v4.3.4.1

  strategy:
    type: Recreate

  env:
    TZ: UTC

  service:
    port:
      port: 8080

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-triple-strip-prefix@kubernetescrd
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      external-dns.alpha.kubernetes.io/hostname: ""

  tolerations:
    - key: role
      value: storage
      effect: NoSchedule

  nodeSelector:
    node-role.kubernetes.io/storage: ""

  hostPathMounts:
    config:
      enabled: true
      mountPath: /config
      hostPath: /tmp/placeholder
    torrents:
      enabled: true
      setPermissions: false
      mountPath: /mnt/media/torrents
      hostPath: /mnt/media/torrents

  podSecurityContext:
    # kah user
    runAsUser: 568
    # media group
    runAsGroup: 500
