{{- if .Values.traefik.ingressRoute.dashboard.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: traefik-{{ .Values.cluster }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-9.18.1
  name: traefik
spec:
  endpoints:
    - path: /metrics
      targetPort: metrics
  jobLabel: traefik
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-{{ .Values.cluster }}
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: traefik
      helm.sh/chart: traefik-9.18.1
{{- end -}}
