apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cachet-push
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
            - name: cachet-sync
              image: dirtycajunrice/cachet-push:1.0.0
              envFrom:
                - configMapRef:
                    name: cachet-push-env
              env:
                - name: PLEX_URL
                  valueFrom:
                    secretKeyRef:
                      key: plex-url
                      name: cachet
                - name: CACHET_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: cachet-api-key
                      name: cachet
                - name: TAUTULLI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: tautulli-api-key
                      name: cachet
          imagePullSecrets:
            - name: docker-config-json
          restartPolicy: OnFailure
