apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cachet
spec:
  backendType: vault
  vaultMountPoint: kubernetes-do
  vaultRole: vault-auth
  data:
    - name: app-key
      key: kv-v2/data/auth/cachet
      property: app-key
    - name: cachet-api-key
      key: kv-v2/data/auth/cachet
      property: cachet-api-key
    - name: db-password
      key: kv-v2/data/auth/cachet
      property: db-password
    - name: mail-address
      key: kv-v2/data/auth/cachet
      property: mail-address
    - name: mail-password
      key: kv-v2/data/auth/cachet
      property: mail-password
    - name: mail-username
      key: kv-v2/data/auth/cachet
      property: mail-username
    - name: plex-url
      key: kv-v2/data/auth/cachet
      property: plex-url
    - name: tautulli-api-key
      key: kv-v2/data/auth/cachet
      property: tautulli-api-key