apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-cachet
  namespace: cajun-pro
spec:
  version: "11.1"
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
