{{- if .Values.kps.grafana.enabled -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
spec:
  backendType: vault
  dataFrom:
    - kv-v2/data/k8s/monitoring/grafana
{{- end -}}
