apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ printf "%s.prometheus.k8s.cajun.pro" .Values.cluster }}`) && PathPrefix(`/akprox`)
      priority: 50
      services:
        - kind: Service
          name: authentik-outpost
          namespace: ingress
  tls:
    secretName: {{ printf "%s.prometheus.k8s.cajun.pro" .Values.cluster | replace "." "-" }}

