fullnameOverride: seafile

image:
  repository: docker.seadrive.org/seafileltd/seafile-pro-mc
  tag: 8.0.2

imagePullSecrets:
  - name: seafile-registry-creds

service:
  port:
    port: 80

command: [/usr/local/bin/entrypoint.sh]

env:
  SEAFILE_ADMIN_EMAIL: nick@cajun.pro
  SEAFILE_SERVER_HOSTNAME: files.cajun.pro
  DB_HOST: mysql-seafile

envValueFrom:
  DB_ROOT_PASSWD:
    secretKeyRef:
      key: password
      name: mysql-seafile-auth

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "10"
    cert-manager.io/cluster-issuer: le-production
  hosts:
    - host: files.cajun.pro
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts: [files.cajun.pro]
      secretName: files-cajun-pro

persistence:
  config:
    enabled: false
    nameSuffix: ""
    storageClass: cstor-replica-pool
    mountPath: /shared/seafile/conf
    size: 5Gi
    accessMode: ReadWriteOnce
    skipuninstall: true

additionalVolumeMounts:
  - name: data
    mountPath: /shared
    subPath: seafile-data
  - name: entrypoint
    mountPath: /usr/local/bin/entrypoint.sh
    subPath: entrypoint.sh

additionalVolumes:
  - name: data
    nfs:
      path: /mnt/media/seafile
      server: 10.0.10.211
  - name: entrypoint
    configMap:
      name: seafile-config
      defaultMode: 0777
      items:
        - key: entrypoint.sh
          path: entrypoint.sh
