fullnameOverride: seafile

image:
  repository: docker.seadrive.org/seafileltd/seafile-pro-mc
  tag: 8.0.2

imagePullSecrets: seafile-registry-creds

service:
  port:
    port: 80

env:
  SEAFILE_ADMIN_EMAIL: nick@cajun.pro
  SEAFILE_SERVER_HOSTNAME: files.cajun.pro
  DB_HOST: $(MYSQL_SEAFILE_PORT_3306_TCP_ADDR)

envValueFrom:
  DB_ROOT_PASSWD:
    secretKeyRef:
      key: password
      name: mysql-seafile-auth

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "10"
    cert-manager.io/cluster-issuer: le-production
  hosts:
    - host: files.cajun.pro
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts: [files.cajun.pro]
      secretName: files-cajun-pro

persistence:
  config:
    enabled: false
    nameSuffix: ""
    storageClass: cstor-replica-pool
    mountPath: /shared/seafile/conf
    size: 5Gi
    accessMode: ReadWriteOnce
    skipuninstall: true

additionalVolumeMounts:
  - name: data
    mountPath: /shared/seafile

additionalVolumes:
  - name: data
    hostPath:
      path: /mnt/media/seafile
      type: Directory

tolerations:
  - key: role
    value: storage
    effect: NoSchedule

nodeSelector:
  node-role.kubernetes.io/storage: ""
