arr:
  env:
    APP_PORT: "8989"

  image:
    repository: ghcr.io/k8s-at-home/sonarr
    tag: v3.0.6.1342
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  persistence:
    config:
      size: 10Gi
