tautulli:
  fullnameOverride: tautulli
  image:
    repository: tautulli/tautulli
    tag: v2.7.2
  enableServiceLinks: false
  env:
    TZ: UTC
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-4@kubernetescrd
    domainName: nickflix.io
    hosts:
      - hostTpl: '{{ .Values.ingress.domainName }}'
        paths:
          - pathTpl: '{{ printf "/%s" .Values.fullnameOverride }}'
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.ingress.domainName | replace "." "-" }}'
    additionalIngresses:
      - enabled: true
        nameSuffix: "api"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.priority: "15"
        hosts:
          - hostTpl: '{{ .Values.ingress.domainName }}'
            paths:
              - pathTpl: '{{ printf "/%s/api" .Values.fullnameOverride }}'
                pathType: Prefix
        tls:
          - hostsTpl: ['{{ .Values.ingress.domainName }}']
            secretNameTpl: '{{ .Values.ingress.domainName | replace "." "-" }}'
  persistence:
    config:
      enabled: true
      nameSuffix: "-"
      storageClass: rook-ceph-block
      size: 10Gi
      accessMode: ReadWriteOnce
      skipuninstall: true
  nodeSelector:
    cajun.pro/cluster-gen: "2"
