global:
  domainName: nickflix.io

tautulli:
  fullnameOverride: tautulli
  image:
    repository: tautulli/tautulli
    tag: v2.9.7
  enableServiceLinks: false
  env:
    TZ: UTC
  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-4@kubernetescrd
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: '{{ printf "/%s" .Values.fullnameOverride }}'
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}'
    api:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "15"
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: '{{ printf "/%s/api" .Values.fullnameOverride }}'
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}'
  persistence:
    config:
      enabled: true
      nameOverride: "-"
      storageClass: cstor-replica-pool
      size: 10Gi
      accessMode: ReadWriteOnce
      retain: true
