apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php
  name: php
  namespace: cajun-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: php:7.4.4-fpm-alpine3.11
        name: php
        ports:
        - containerPort: 9000
          protocol: TCP
          name: http
        volumeMounts:
          - name: www
            mountPath: /usr/share/nginx
      hostname: php
      nodeSelector:
        node-role.k8s.cajun.pro/aws: "true"
      restartPolicy: Always
      volumes:
        - name: www
          hostPath:
            path: /mnt/kubernetes/nginx/www
            type: Directory

