overseerr:
  fullnameOverride: overseerr
  image:
    repository: ghcr.io/sct/overseerr
    tag: 1.23.2
    pullPolicy: IfNotPresent
  env:
    TZ: America/Chicago
    LOG_LEVEL: debug
  ingress:
    enabled: true
    domainPrimary: request.cajun.pro
    domainSecondary: overseerr.nickflix.io
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - hostTpl: '{{ .Values.ingress.domainPrimary }}'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ .Values.ingress.domainPrimary }}']
        secretNameTpl: '{{ .Values.ingress.domainPrimary | replace "." "-" }}'
    additionalIngresses:
      - enabled: true
        nameSuffix: "test"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.priority: "10"
          cert-manager.io/cluster-issuer: le-production
        hosts:
          - hostTpl: '{{ .Values.ingress.domainSecondary }}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hostsTpl: ['{{ .Values.ingress.domainSecondary }}']
            secretNameTpl: '{{ .Values.ingress.domainSecondary | replace "." "-" }}'
  persistence:
    config:
      enabled: true
      nameSuffix: "-"
      storageClass: rook-ceph-block
      size: 10Gi
      accessMode: ReadWriteOnce
      skipuninstall: true
  resources:
    requests:
      cpu: 100m
      memory: 128m
  nodeSelector:
    cajun.pro/cluster-gen: "2"
