global:
  domainPrimary: request.cajun.pro
  domainSecondary: overseerr.nickflix.io

overseerr:
  fullnameOverride: overseerr
  image:
    repository: ghcr.io/sct/overseerr
    tag: 1.26.1
    pullPolicy: IfNotPresent
  env:
    TZ: America/Chicago
    LOG_LEVEL: debug
  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - host: '{{ .Values.global.domainPrimary }}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainPrimary }}']
          secretName: '{{ .Values.global.domainPrimary | replace "." "-" }}'
    test:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - host: '{{ .Values.global.domainSecondary }}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainSecondary }}']
          secretName: '{{ .Values.global.domainSecondary | replace "." "-" }}'
  persistence:
    config:
      enabled: true
      nameOverride: "-"
      storageClass: cstor-replica-pool
      size: 10Gi
      accessMode: ReadWriteOnce
      retain: true
  resources:
    requests:
      cpu: 100m
      memory: 128m
