apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-critical-global
spec:
  generators:
    - git:
        repoURL: https://github.com/DirtyCajunRice/GitOps-Argo-CD.git
        revision: refactor
        directories:
          - path: "cluster-critical/cloud/vault/*"
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: cluster-critical
      source:
        path: '{{ path }}'
        targetRevision: refactor
        repoURL: https://github.com/DirtyCajunRice/GitOps-Argo-CD.git
        helm:
          valueFiles:
            - values.yaml
      destination:
        name: do
        namespace: vault
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=background
