apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-haste-server
  namespace: cajun-pro
spec:
  version: 6.0.6
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          app: haste-server
        interval: 10s
  terminationPolicy: DoNotTerminate
