global:
  domainName: cajun.pro

image:
  repository: containous/whoami
  tag: v1.5.0

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - host: '{{ printf "whoami-%s.%s" .Values.global.cluster .Values.global.domainName }}'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: ['{{ printf "whoami-%s.%s" .Values.global.cluster .Values.global.domainName }}']
        secretName: '{{ printf "whoami-%s.%s" .Values.global.cluster .Values.global.domainName | replace "." "-" }}'
