apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: php:7.4.4-fpm-alpine3.11
        name: php
        ports:
        - containerPort: 9000
          protocol: TCP
          name: http
      restartPolicy: Always

