arr:
  env:
    TZ: America/Chicago

  envValueFrom:
    APP_NAME:
      fieldRef:
        fieldPath: metadata.labels[app.kubernetes.io/instance]

  ingress:
    domainName: "nickflix.io"
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: ingress-authentik-outpost@kubernetescrd
      traefik.ingress.kubernetes.io/router.priority: "10"

    hosts:
      - hostTpl: '{{ .Values.ingress.domainName }}'
        paths:
          - pathTpl: '{{ printf "/%s" (replace .Values.fullnameOverride "-" "/") }}'
            pathType: Prefix
    tls:
      - hostsTpl: ['{{ .Values.ingress.domainName }}']
        secretNameTpl: '{{ .Values.ingress.domainName | replace "." "-" }}'

  persistence:
    config:
      enabled: true
      nameSuffix: "-"
      storageClass: cstor-replica-pool
      size: 10Gi
      accessMode: ReadWriteOnce
      skipuninstall: true
    emptydir:
      enabled: true
      emptyDir:
        enabled: true
      mountPath: /mnt/media/torrents/incomplete

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 500

  probes:
    liveness:
      spec:
        exec:
          command:
            - /usr/bin/env
            - bash
            - -c
            - curl --fail localhost:${APP_PORT}/${APP_NAME/-//}/api/v3/system/status?apiKey=`IFS=\> && while
              read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
