nextcloud:
  fullnameOverride: nextcloud
  image:
    repository: nextcloud
    tag: 21.0.1-apache
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-nextcloud-dav-redirect@kubernetescrd,cajun-pro-hsts@kubernetescrd
      cert-manager.io/cluster-issuer: le-production
    tls:
      - hosts:
          - files.cajun.pro
        secretName: files-cajun-pro
  nextcloud:
    host: files.cajun.pro
    tableprefix: oc_
    mail:
      enabled: true
      fromAddress: no-reply
      domain: cajun.pro
      smtp:
        host: smtp.gmail.com
        secure: tls
        port: 587
        authtype: LOGIN
    extraVolumes:
      - name: data
        hostPath:
          path: /mnt/media/nextcloud_data
    extraVolumeMounts:
      - mountPath: /data
        name: data
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: mysql
    host: mysql-nextcloud.cajun-pro.svc
    database: nextcloud
    existingSecret:
      enabled: true
      secretName: mysql-nextcloud-auth
      usernameKey: username
      passwordKey: password
  cronjob:
    enabled: false
  persistence:
    enabled: true
    storageClass: rook-cephfs
    accessMode: ReadWriteMany
    size: 10Gi
  metrics:
    enabled: true
    https: true
  nodeSelector:
    kubernetes.io/hostname: node4.k8s.cajun.pro
