argo-cd:
  fullnameOverride: argocd
  installCRDs: false

  global:
    image:
      tag: v1.8.7

  controller:
    replicas: 1
    enableStatefulSet: ftrue
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      rules:
        enabled: false
        spec:
          - alert: ArgoAppMissing
            expr: |
              absent(argocd_app_info)
            for: 15m
            labels:
              severity: critical
            annotations:
              summary: "[ArgoCD] No reported applications"
              description: >
                ArgoCD has not reported any applications data for the past 15 minutes which
                means that it must be down or not functioning properly.  This needs to be
                resolved for this cloud to continue to maintain state.
          - alert: ArgoAppNotSynced
            expr: |
              argocd_app_info{sync_status!="Synced"} == 1
            for: 12h
            labels:
              severity: warning
            annotations:
              summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
              description: >
                The application [{{`{{$labels.name}}`}} has not been synchronized for over
                12 hours which means that the state of this cloud has drifted away from the
                state inside Git.
    resources:
      requests:
        cpu: 250m
        memory: 300Mi

  dex:
    enabled: false

  server:
    configEnabled: true
    extraArgs:
      - --insecure
    config:
      url: https://argocd.cajun.pro
      application.instanceLabelKey: argocd.argoproj.io/instance
      oidc.config: |
        name: OIDC
        issuer: https://accounts.google.com
        clientID: 594747869011-98q8bqo6sfpsivnr1ud80j9aaans03mf.apps.googleusercontent.com
        clientSecret: t7gQyljbegUsJOQtjh-iOYSL
        requestedScopes:
          - openid
          - profile
          - email
      resource.compareoptions: |
        ignoreAggregatedRoles: true
      resource.customizations: |
        core/Service:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
        networking.k8s.io/Ingress:
          health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
    rbacConfig:
      policy.default: role:readonly
      scopes: '[email, group]'
      policy.csv: |
        g, nick@cajun.pro, role:admin
        g, nstgermain@ea.com, role:admin
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - argocd.cajun.pro
      tls:
        - secretName: argocd-cajun-pro
          hosts: [argocd.cajun.pro]
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 75
      targetMemoryUtilizationPercentage: 75
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-repo-server
              topologyKey: kubernetes.io/hostname
            weight: 100
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    volumes:
      - name: custom
        emptyDir: {}
    initContainers:
      - name: copy-custom-kubectl
        image: "bitnami/kubectl:1.20.5"
        command: ["cp", "/opt/bitnami/kubectl", "/custom"]
        volumeMounts:
          - mountPath: /custom
            name: custom
    volumeMounts:
      - mountPath: /usr/local/bin/kubectl
        name: custom
        subPath: kubectl
podDisruptionBudget:
  enabled: true
  minAvailable: 1
