argo-cd:
  fullnameOverride: argocd
  installCRDs: false
  global:
    image:
      tag: v1.8.1
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 300Mi
  server:
    extraArgs:
      - --insecure
    config:
      url: https://argocd.cajun.pro
      application.instanceLabelKey: argocd.argoproj.io/instance
      accounts.cajunguest: login
      oidc.config: |
        name: OIDC
        issuer: https://accounts.google.com
        clientID: 594747869011-98q8bqo6sfpsivnr1ud80j9aaans03mf.apps.googleusercontent.com
        clientSecret: t7gQyljbegUsJOQtjh-iOYSL
        requestedScopes:
          - openid
          - profile
          - email
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, nick@cajun.pro, role:admin
        g, nstgermain@ea.com, role:admin
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - argocd.cajun.pro
      tls:
        - secretName: argocd-cajun-pro
          hosts:
            - argocd.cajun.pro
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 75
      targetMemoryUtilizationPercentage: 75
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-repo-server
              topologyKey: kubernetes.io/hostname
            weight: 100
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  dex:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
podDisruptionBudget:
  enabled: true
  minAvailable: 1
