apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.conreq.fullnameOverride }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes-home
  vaultRole: vault-auth
  data:
    - name: sonarr_key
      key: kv-v2/data/auth/sonarr
      property: api-key-1080p
    - name: radarr_key
      key: kv-v2/data/auth/radarr
      property: api-key-1080p
    - name: tmdb_key
      key: kv-v2/data/auth/tmdb
      property: api-key
