apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: silence-among-us
spec:
  backendType: vault
  vaultMountPoint: kubernetes-do
  vaultRole: vault-auth
  data:
    - name: host
      key: kv-v2/data/auth/silence-among-us
      property: host
    - name: discord-token
      key: kv-v2/data/auth/silence-among-us
      property: discord-token
    - name: database-username
      key: kv-v2/data/auth/silence-among-us
      property: database-username
    - name: database-password
      key: kv-v2/data/auth/silence-among-us
      property: database-password
