apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-home
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: utility
    name: home
  project: default
  source:
    path: cert-manager
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - home-values.yaml
    repoURL: git@github.com:DirtyCajunRice/GitOps-Argo-CD.git
  syncPolicy:
    automated: {}
