conreq:
  fullnameOverride: "conreq"
  image:
    organization: itscontained
    repository: conreq
    tag: c2c6367
    pullPolicy: Always
  env:
    TZ: America/Chicago
    PUID: "1000"
    PGID: "1000"
    DATA_DIR: "/config"
    ALLOWED_HOSTS: "conreq.cajun.pro"
    SONARR_URL: "http://sonarr.cajun-pro.svc:8989/sonarr"
    RADARR_URL: "http://radarr.cajun-pro.svc:7878/radarr"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.priority: "10"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: le-production
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-google-auth@kubernetescrd
    tls:
      - hosts: [conreq.cajun.pro]
        secretName: conreq-cajun-pro
    hosts:
      - host: conreq.cajun.pro
        paths:
          - path: /
            pathType: Prefix
  service:
    port: 8000
  persistence:
    type: statefulset
    config:
      accessMode: ReadWriteMany
      size: 10Gi
      storageClass: rook-cephfs
  nodeSelector:
    cajun.pro/cluster-gen: "2"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 2Gi
