global:
  cluster: do
  fullnameOverride: red-varken

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/external/discord
    secretObjects: true
    objects:
      - name: varken-bot-token

image:
  repository: phasecorex/red-discordbot
  tag: latest@sha256:558df9ec83fc03b4948a62201575f2d90fbf72d4926fdd867370c8b56c1e26bf

replicas: 1

env:
  PREFIX: "!"
  PUID: "1000"
  PGID: "1000"
  TOKEN:
    secretKeyRef:
      key: varken-bot-token
      name: red-discordbot-varken

service:
  main:
    enabled: false

persistence:
  data:
    enabled: true
    mountPath: /data
    nameOverride: "-"
    storageClass: do-block-storage
    size: 1Gi
    accessMode: ReadWriteOnce
    retain: true
  secrets:
    enabled: true
    type: custom
    mountPath: /mnt/secrets
    readOnly: true
    volumeSpec:
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: red-discordbot-varken

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
