apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr-1080p
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: cajun-pro
    server: https://node5.k8s.cajun.pro:6443
  project: default
  source:
    path: sonarr
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-1080p.yaml
    repoURL: git@github.com:DirtyCajunRice/GitOps-Argo-CD.git
  syncPolicy:
    automated: {}
