apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes-do
  vaultRole: vault-auth
  data:
    - name: admin-user
      key: kv-v2/data/auth/statping
      property: admin-user
    - name: admin-password
      key: kv-v2/data/auth/statping
      property: admin-password
    - name: admin-email
      key: kv-v2/data/auth/common
      property: email
    - name: username
      key: kv-v2/data/auth/statping
      property: db-username
    - name: password
      key: kv-v2/data/auth/statping
      property: db-password
