apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres-statping
spec:
  version: "11.11"
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  authSecret:
    name: statping
  podTemplate:
    spec:
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          app: statping
        interval: 10s
  terminationPolicy: DoNotTerminate
