apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: xbackbone
spec:
  provider: vault
  parameters:
    roleName: "csi-secrets-store"
    vaultAddress: https://vault.cajun.pro
    vaultKubernetesMountPath: kubernetes/do
    objects: |
      - objectName: config.php
        secretKey: config.php
        secretPath: kv-v2/data/k8s/cajun-pro/xbackbone

