apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-home
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: utility
    name: home
  project: default
  source:
    path: external-dns
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      values: |
        txtOwnerId: "home"
        nodeSelector:
          cajun.pro/cluster-gen: "2"
    repoURL: git@github.com:DirtyCajunRice/GitOps-Argo-CD.git
  #syncPolicy:
  #  automated: {}
