global:
  cluster: do
  fullnameOverride: ae-api

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/cajun-pro/new-world-exporter/ae-bot
    objects:
      - name: .client-id
      - name: .client-token
      - name: .mongo-uri
      - name: .server-info-url

image:
  repository: bodnapa/azoth-empire-graphql-api
  tag: v1.3.21

replicas: 1

env:
  GUILD_ID: '654661232497786893'

service:
  main:
    ports:
      http:
        port: 4000

ingress:
  main:
    enabled: false

persistence:
  secrets:
    enabled: true
    type: custom
    mountPath: /app/secrets
    readOnly: true
    volumeSpec:
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: ae-bot

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
