global:
  fullnameOverride: new-world-api

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/cajun-pro/new-world-exporter/ae-bot
    secretObjects: true
    objects:
      - name: .client-id
      - name: .client-token
      - name: .mongo-uri
      - name: .server-info-url
      - name: .client-secret

image:
  repository: bodnapa/azoth-empire-graphql-api

service:
  main:
    ports:
      http:
        port: 4000
