global:
  fullnameOverride: new-world-api

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/cajun-pro/new-world-exporter/ae-bot
    secretObjects: true
    objects:
      - name: .client-id
      - name: .client-token
      - name: .mongo-uri
      - name: .server-info-url
      - name: .client-secret

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - host: 'api.newworld.k8s.cajun.pro'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: ['api.newworld.k8s.cajun.pro']
        secretName: 'api-newworld-k8s-cajun-pro'

image:
  repository: bodnapa/azoth-empire-graphql-api

service:
  main:
    ports:
      http:
        port: 4000
