apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rtorrent2
  labels:
    app: rtorrent2
spec:
  selector:
    matchLabels:
      app: rtorrent2
  endpoints:
  - port: metrics

