apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: auto-voice-channels
spec:
  backendType: vault
  vaultMountPoint: kubernetes-do
  vaultRole: vault-auth
  data:
    - name: config.json
      key: kv-v2/data/auth/auto-voice-channels
      property: config.json
