apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-cachet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cachet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-cachet
    spec:
      nodeSelector:
        node-role.k8s.cajun.pro/aws: "true"
      hostname: postgres
      restartPolicy: Always
      containers:
      - name: postgres
        image: postgres:9.5.15-alpine
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-cachet-env
        volumeMounts:
             - mountPath: /var/lib/postgresql/data
               name: data
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      volumes:
        - name: data
          hostPath:
            path: /mnt/kubernetes/postgres
            type: Directory
