cluster: do

traefik:
  additionalArguments:
    - "--providers.kubernetesingress.ingressendpoint.hostname=traefik-do.k8s.cajun.pro"
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-name: traefik
      service.beta.kubernetes.io/do-loadbalancer-protocol: tcp
      service.beta.kubernetes.io/do-loadbalancer-size-slug: lb-small
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "2"
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "10"
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "3"
  pilot:
    token: "cac885fb-0bee-4b6e-a316-ceaf61cab202"
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5

traefik-forward-auth:
  authHost: cajun.pro
  ingress:
    hosts:
      - host: cajun.pro
        paths: [/_oauth]
    tls:
      - hosts: [cajun.pro]
        secretName: cajun-pro
