radarr:
  radarr:
    fullnameOverride: "radarr"
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.priority: "10"
      hosts:
        - host: nickflix.io
          paths:
            - path: /radarr
              pathType: Prefix
      extraIngresses:
        - enabled: true
          nameSuffix: "api"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.priority: "15"
          hosts:
            - host: nickflix.io
              paths:
                - path: /radarr/api
                  pathType: Prefix
          tls:
            - hosts: [nickflix.io]
              secretName: nickflix-io
