
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silence-among-us
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silence-among-us
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: silence-among-us
    spec:
      restartPolicy: Always
      containers:
        - name: silence-among-us
          image: ghcr.io/tanndev/silence-among-us:2.7.0-beta.2
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          env:
            - name: SECURE
              value: "true"
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: silence-among-us
                  key: host
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: silence-among-us
                  key: discord-token
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: silence-among-us
                  key: database-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: silence-among-us
                  key: database-password
            - name: DATABASE_URL
              value: "http://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@localhost:5984"
            - name: CUSTOM_PRESENCE_NAME
              value: "Among Us | .au help"
            - name: CUSTOM_PRESENCE_TYPE
              value: "PLAYING"
        - name: couchdb
          image: couchdb:3.1
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: silence-among-us
                  key: database-username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: silence-among-us
                  key: database-password
          volumeMounts:
            - name: data
              mountPath: /opt/couchdb/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: silence-among-us
