metallb:
  prometheus:
    serviceMonitor:
      enabled: true
  configInline:
    peers:
      - peer-address: 10.0.10.1
        peer-asn: 64512
        my-asn: 64512
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 10.0.10.150-10.0.10.200  
        avoid-buggy-ips: true