loki-stack:
  fullnameOverride: loki-stack
  loki:
    fullnameOverride: loki
    nodeSelector:
      cajun.pro/cluster-gen: "2"
    serviceMonitor:
      enabled: true
  promtail:
    fullnameOverride: promtail
    serviceMonitor:
      enabled: true

