---
apiVersion: v1
kind: Service
metadata:
  name: nvidia-smi-exporter
  labels:
    app: nvidia-smi-exporter
spec:
  ports:
  - port: 9454
    targetPort: 9454
    protocol: TCP
    name: metrics
  selector:
    app: nvidia-smi-exporter
