apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-smi-exporter
  labels:
    app: nvidia-smi-exporter
spec:
  selector:
    matchLabels:
      app: nvidia-smi-exporter
  endpoints:
  - port: metrics

