apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nick@cajun.pro
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - "nickflix.io"
            - "cajun.pro"
            - "itscontained.io"
        dns01:
          route53:
            region: us-east-1
