apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres-authentik
spec:
  version: "13.2"
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          app: authentik
        interval: 10s
  terminationPolicy: DoNotTerminate
