external-dns:
  fullnameOverride: external-dns
  image:
    registry: docker.io
    repository: bitnami/external-dns
    tag: 0.7.6-debian-10-r63
  sources:
    - crd
    - service
    - ingress
  provider: aws
  aws:
    credentials:
      secretName: aws-creds
    evaluateTargetHealth: false
  domainFilters:
    - "nickflix.io"
    - "cajun.pro"
    - "itscontained.io"
  interval: "1m"
  logLevel: debug
  logFormat: json
  txtPrefix: "_."
  replicas: 1
  crd:
    create: true
  metrics:
    serviceMonitor:
      enabled: true
