fullnameOverride: red-varken

global:
  cluster: do

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/external/discord
    secretObjects: true
    objects:
      - name: varken-bot-token

image:
  repository: phasecorex/red-discordbot
  tag: latest@sha256:3a2a0c903e5f4300c8248ab88225dd32997c872be3e4b5caffe6cf22fa21f0da

replicas: 1

envValueFrom:
  TOKEN:
    secretKeyRef:
      key: varken-bot-token
      name: red-discordbot-varken

env:
  PREFIX: "!"
  PUID: "1000"
  PGID: "1000"

service:
  enabled: false

additionalVolumeMounts:
  - name: secrets
    mountPath: /mnt/secrets
    readOnly: true

additionalVolumes:
  - name: secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: red-discordbot-varken

persistence:
  data:
    enabled: true
    mountPath: /data
    nameSuffix: "-"
    storageClass: do-block-storage
    size: 1Gi
    accessMode: ReadWriteOnce
    skipuninstall: true

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
