global:
  cluster: do
  fullnameOverride: red-varken

addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/external/discord
    secretObjects: true
    objects:
      - name: varken-bot-token

image:
  repository: phasecorex/red-discordbot
  tag: latest@sha256:bfa8f0d6aac35ab2b7e0613be5331d24ba778ac2f54622c065e6a5e7005c6b2a

replicas: 1

env:
  PREFIX: "!"
  PUID: "1000"
  PGID: "1000"
  TOKEN:
    secretKeyRef:
      key: varken-bot-token
      name: red-discordbot-varken

service:
  main:
    enabled: false

persistence:
  data:
    enabled: true
    mountPath: /data
    nameOverride: "-"
    storageClass: do-block-storage
    size: 1Gi
    accessMode: ReadWriteOnce
    retain: true
  secrets:
    enabled: true
    type: custom
    mountPath: /mnt/secrets
    readOnly: true
    volumeSpec:
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: red-discordbot-varken

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
