cert-manager:
  fullnameOverride: cert-manager
  prometheus:
    servicemonitor:
      enabled: "true"
  nodeSelector:
    cajun.pro/cluster-gen: 2
  installCRDs: true
  volumes:
    - name: aws-credentials
      secret:
        defaultMode: 420
        secretName: aws-creds
  volumeMounts:
    - mountPath: /.aws
      name: aws-credentials
      readOnly: true
  webhook:
    nodeSelector:
      cajun.pro/cluster-gen: 2
  cainjector:
    nodeSelector:
      cajun.pro/cluster-gen: 2
