apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: loki-basic-auth
spec:
  backendType: vault
  vaultMountPoint: kubernetes-home
  vaultRole: vault-auth
  data:
    - name: users
      key: kv-v2/data/auth/loki
      property: basic-auth
